<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <DistributionLicense Include="$(SolutionDir)COPYING.GPLv3" />
    <DistributionLicense Include="$(SolutionDir)COPYING.LGPLv3" />
    <DistributionLicense Include="$(SolutionDir)THIRD_PARTY_NOTICES.md" />
  </ItemGroup>
  <Target Name="CopyDistributionLicenses"
    AfterTargets="Build"
    Inputs="@(DistributionLicense)"
    Outputs="@(DistributionLicense -> '$(OutDir)docs\%(Filename)%(Extension)')">
    <Copy
      SourceFiles="@(DistributionLicense)"
      DestinationFolder="$(OutDir)docs"
      SkipUnchangedFiles="true"
    />
  </Target>
</Project>
